env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - 'next'
  - 'prettier'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - material-ui
rules:
  {
    'react/react-in-jsx-scope': 'off',
    'require-jsdoc': 'off',
    'max-len': 'off',
    'react/prop-types': 'off',
    'new-cap': 'off',
  }
globals: { 'React': 'writable' }
settings:
  react: { version: detect }
