version: '3.8'

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - 3000:3000
  environment:
   - SERVER_PORT=3000
  volumes:
   - ./:/app
  command: yarn dev

 postgres:
  image: postgres:13.2
  volumes:
  - postgres:/var/lib/postgresql/data
  environment:
   - POSTGRES_DB=facilitator
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  ports:
   - 5432:5432
  expose:
   - 5432

volumes:
 postgres:
