version: '3.8'

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - 3000:3000
  environment:
   - SERVER_PORT=3000
  volumes:
   - ./:/app
  command: yarn dev

 mongo:
  image: mongo:4.4.4
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
 mongo-express:
  image: mongo-express:latest
  ports:
   - 8081:8081
volumes:
 mongodb:
 mongodb_config:
 mongo-express:
